services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      # LEEMOS LA VARIABLE DEL ARCHIVO .ENV
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_URL: "http://localhost:3000"
    depends_on:
      - db
    # Comando para regenerar prisma si cambias el schema durante el desarrollo
    command: sh -c "npx prisma generate && pnpm dev"

  # --- BASE DE DATOS MYSQL ---
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      # AQUÍ TAMBIÉN USAMOS LAS VARIABLES DEL .ENV
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- PHPMYADMIN (Gestor Visual) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data: